import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Datenschutz | Leisure Workspace", description: "Datenschutzhinweise für Leisure Workspace und die lokal arbeitenden Tools." };

export default function DatenschutzPage() {
  return <LegalPage eyebrow="DATENSCHUTZ" title="Datenschutzerklärung" updated="6. September 2026" locale="de" englishPath="/en/privacy" germanPath="/datenschutz">
    <section><h2>1. Verantwortlicher</h2><address>Stefan Burian<br />Ahrfeldstraße 68<br />45136 Essen<br />Deutschland</address><p>Telefon: <a href="tel:+4917661562513">+49 176 61562513</a><br />E-Mail: <a href="mailto:contact@stefanburian.com">contact@stefanburian.com</a></p></section>
    <section><h2>2. Grundsatz</h2><p>Leisure Workspace ist bewusst datensparsam aufgebaut. Für die Nutzung der Tools ist kein Benutzerkonto und kein Login erforderlich. Wir betreiben kein eigenes Nutzer-Tracking und setzen auf dieser Website keine eigenen Analyse- oder Marketingdienste ein.</p></section>
    <section><h2>3. Verarbeitung innerhalb der Tools</h2><p>Eingaben, Berechnungen und Projekte aus den Tools werden nicht an uns übermittelt und nicht in einer Cloud-Datenbank von Leisure Workspace gespeichert. Die Verarbeitung erfolgt lokal im Browser beziehungsweise auf dem verwendeten Endgerät.</p><p>Wenn ein Tool eine Exportfunktion anbietet, wird eine separate Datei lokal erstellt und auf dem Endgerät gespeichert. Über Speicherort, Weitergabe und Löschung dieser Datei entscheiden allein die Nutzerinnen und Nutzer. Lokal gespeicherte Inhalte können durch das Löschen der Browser- oder Gerätedaten entfernt werden.</p></section>
    <section><h2>4. Hosting und Server-Logdaten</h2><p>Beim Aufruf der Website werden durch die technische Hosting-Infrastruktur zwangsläufig Verbindungsdaten verarbeitet. Dazu können insbesondere IP-Adresse, Datum und Uhrzeit des Abrufs, aufgerufene Seite, Referrer, Browsertyp und Betriebssystem gehören. Diese Verarbeitung ist erforderlich, um die Website sicher und zuverlässig bereitzustellen, und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p><p>Die Website wird über OpenAI Sites bereitgestellt; dabei kann Infrastruktur von Cloudflare eingesetzt werden. Ergänzende Informationen finden Sie in der <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noreferrer">Datenschutzerklärung von OpenAI</a> und der <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Datenschutzerklärung von Cloudflare</a>.</p></section>
    <section><h2>5. Cookies und lokale Speicherung</h2><p>Leisure Workspace setzt keine eigenen Cookies zu Analyse-, Werbe- oder Profilingzwecken. Technisch notwendige Speichermechanismen können durch die Hosting-Infrastruktur oder den Browser verwendet werden. Von den Tools lokal gespeicherte Informationen verbleiben auf dem verwendeten Endgerät und sind keine Cloud-Speicherung durch Leisure Workspace.</p></section>
    <section><h2>6. Kontaktaufnahme</h2><p>Wenn Sie uns per E-Mail oder Telefon kontaktieren, verarbeiten wir Ihre übermittelten Angaben zur Bearbeitung der Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vorvertraglichen oder vertraglichen Anliegen, ansonsten Art. 6 Abs. 1 lit. f DSGVO. Die Daten werden gelöscht, sobald der Zweck entfällt und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p></section>
    <section><h2>7. Ihre Rechte</h2><p>Sie haben nach Maßgabe der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Sie haben außerdem das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig ist insbesondere die Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen.</p></section>
    <section><h2>8. Aktualisierung</h2><p>Diese Datenschutzerklärung wird angepasst, wenn sich die Website, die eingesetzten Tools oder die technische Bereitstellung ändern.</p></section>
  </LegalPage>;
}
